// DO NOT EDIT - Auto-generated by export_models.py
// Generated: 2026-09-30T11:06:34.894690
// KitchenGuard CSM - Waste Classification Helper for Android

package com.kitchenguard.csm.utils;

import android.content.Context;
import org.json.JSONObject;
import java.util.HashMap;
import java.util.Map;

/**
 * Waste Classification Results
 */
public class WasteClassificationResult {
    public String category;           // SPOILED, EXPIRED, etc.
    public double confidence;         // 0.0 to 1.0
    public boolean isApproved;        // Above confidence threshold?
    public String actionRecommendation; // Action guidance text
}

/**
 * Mobile Waste Classifier Helper
 * Implements simplified prediction logic compatible with mobile environment
 * Uses rule-based extraction matching TF-IDF key features
 */
public class WasteClassifierMobileHelper {
    
    private static final double CONFIDENCE_THRESHOLD = 0.85;
    
    // Simplified keyword mapping (matches TF-IDF important features)
    private static final Map<String, String[]> KEYWORD_MAPPING = new HashMap<>();
    
    static {
        KEYWORD_MAPPING.put("SPOILED", new String[]{
            "berjamur", "busuk", "lendir", "bau bangkai", "menghitam", "mencair"
        });
        
        KEYWORD_MAPPING.put("EXPIRED", new String[]{
            "kedaluwarsa", "expired date", "MHD", "lewat batas", "best before"
        });
        
        KEYWORD_MAPPING.put("CONTAMINATED", new String[]{
            "terkontaminasi", "hair", "lantai kotor", "serangga", 
            "debu", "tertetes darah", "bersentuhan pisau kotor"
        });
        
        KEYWORD_MAPPING.put("OVERCOOKED", new String[]{
            "gosong", "hangus", "kelewat matang", "pahit", "overdone"
        });
        
        KEYWORD_MAPPING.put("PREP_WASTE", new String[]{
            "trimming", "kulit", "bonggol", "sisa preparasi", "yield loss",
            "peeling", "sisa pemotongan", "tulang", "lemak berlebih"
        });
        
        KEYWORD_MAPPING.put("SURPLUS", new String[]{
            "lebihan", "tidak terjual", "sisa display", "overproduksi",
            "tidak habis", "melebihan porsi"
        });
    }
    
    /**
     * Perform waste classification on mobile device
     * Uses keyword matching as proxy for TF-IDF scoring
     * Suitable for low-resource environments without full ML pipeline
     */
    public WasteClassificationResult classifyWaste(String rawText) {
        String textLower = rawText.toLowerCase();
        
        // Find best matching category based on keyword density
        String bestCategory = null;
        double maxScore = 0.0;
        
        for (Map.Entry<String, String[]> entry : KEYWORD_MAPPING.entrySet()) {
            int keywordCount = 0;
            for (String keyword : entry.getValue()) {
                if (textLower.contains(keyword)) {
                    keywordCount++;
                }
            }
            
            // Normalize score by number of keywords
            double normalizedScore = (double) keywordCount / entry.getValue().length;
            
            if (normalizedScore > maxScore) {
                maxScore = normalizedScore;
                bestCategory = entry.getKey();
            }
        }
        
        // Convert score to confidence-like value
        double confidence = Math.min(maxScore * 1.5, 1.0);  // Scale up but cap at 1.0
        
        // Determine approval status
        boolean isApproved = confidence >= CONFIDENCE_THRESHOLD;
        
        // Get action recommendation
        String action = getActionRecommendation(bestCategory);
        
        return new WasteClassificationResult() {
            this.category = bestCategory != null ? bestCategory : "UNCERTAIN";
            this.confidence = confidence;
            this.isApproved = isApproved;
            this.actionRecommendation = action;
        };
    }
    
    private String getActionRecommendation(String category) {
        switch (category) {
            case "SPOILED":
                return "Reject & Pisahkan segera dari area penyimpanan dingin." +
                       " Buang ke limbah organik untuk mencegah kontaminasi silang.";
            case "EXPIRED":
                return "Tarik dari inventori FIFO. Buang dan catat tanggal kadaluarsa" +
                       " serta nomor batch supplier untuk klaim retur.";
            case "PREP_WASTE":
                return "Timbang sisa prep (yield loss). Masukkan ke dalam kalkulasi" +
                       " efisiensi bahan butchery/vegetable station.";
            case "OVERCOOKED":
                return "Catat insiden kesalahan masak. Laporkan ke Sous Chef/Head Chef" +
                       " untuk evaluasi resep & suhu operasional.";
            case "CONTAMINATED":
                return "BAHAYA FOOD SAFETY! Segera reject seluruh bahan yang terpapar" +
                       " dan lakukan sterilisasi area/peralatan.";
            case "SURPLUS":
                return "Evaluasi porsi berlebih. Alihkan ke program staff meal jika higienis" +
                       " atau catat overproduction write-off.";
            default:
                return "Lakukan verifikasi manual oleh supervisor.";
        }
    }
    
    /**
     * Check if text contains valid keywords
     */
    public boolean hasValidKeywords(String text) {
        for (String[] keywords : KEYWORD_MAPPING.values()) {
            for (String keyword : keywords) {
                if (text.toLowerCase().contains(keyword)) {
                    return true;
                }
            }
        }
        return false;
    }
}
