// DO NOT EDIT - Auto-generated by export_models.py
// Generated: 2026-09-30T11:06:34.895689
package com.csm.kitchenguard.utils.ai;

/**
 * Skin Detection Result
 * Uses Fitzpatrick Skin Phototype scale (medical standard)
 * Focus on SUN PROTECTION NEEDS rather than racial categorization
 */
public class SkinDetectionResult {
    public String fitzpatrickType;      // I, II, III, IV
    public String protectionLevel;      // SPF recommendation
    public String sunSensitivity;       // EXTREME/HIGH/MODERATE/LOW
    public boolean requiresCoverage;    // Should wear gloves/clothing?
}

/**
 * Mobile Fitzpatrick Skin Type Estimator
 * Medical-standard approach for sun sensitivity assessment
 * Avoids biased FAIR/NOT_FAIR binary classification
 */
public class FitzpatrickSkinEstimator {
    
    /**
     * Estimate Fitzpatrick type from RGB values
     * Based on dermatological research and color analysis
     * 
     * @param r Red component (0-255)
     * @param g Green component (0-255)
     * @param b Blue component (0-255)
     * @return Skin detection result with medical recommendations
     */
    public SkinDetectionResult estimateSkinType(float r, float g, float b) {
        
        // Calculate brightness index (overall lightness)
        double brightnessIndex = (r + g + b) / 3.0;
        
        // Calculate saturation-like metric (variance between channels)
        double colorVariance = Math.max(r, Math.max(g, b)) - Math.min(r, Math.min(g, b));
        
        SkinDetectionResult result = new SkinDetectionResult();
        
        // Fitzpatrick Type I - Very Fair
        // Always burns, never tans - high R value (>240)
        if (brightnessIndex > 240 && colorVariance < 20) {
            result.fitzpatrickType = "I";
            result.protectionLevel = "SPF 50+, Complete coverage required";
            result.sunSensitivity = "EXTREME";
            result.requiresCoverage = true;
        }
        // Fitzpatrick Type II - Fair  
        // Burns easily, tans minimally (R: 220-240)
        else if (brightnessIndex >= 220 && brightnessIndex <= 240) {
            result.fitzpatrickType = "II";
            result.protectionLevel = "SPF 30+, Coverage recommended";
            result.sunSensitivity = "HIGH";
            result.requiresCoverage = true;
        }
        // Fitzpatrick Type III - Light
        // Burns moderately, tans uniformly (R: 200-220)
        else if (brightnessIndex >= 200 && brightnessIndex < 220) {
            result.fitzpatrickType = "III";
            result.protectionLevel = "SPF 25-30, Partial coverage needed";
            result.sunSensitivity = "MODERATE";
            result.requiresCoverage = false;
        }
        // Fitzpatrick Type IV - Medium/Olive
        // Burns minimally, tans well (R: 180-200)
        else if (brightnessIndex >= 180 && brightnessIndex < 200) {
            result.fitzpatrickType = "IV";
            result.protectionLevel = "SPF 15-20, Standard protection";
            result.sunSensitivity = "LOW";
            result.requiresCoverage = false;
        }
        // Outside typical range - unable to determine reliably
        else {
            result.fitzpatrickType = "UNKNOWN";
            result.protectionLevel = "Cannot determine - manual assessment needed";
            result.sunSensitivity = "UNKNOWN";
            result.requiresCoverage = false;
        }
        
        return result;
    }
    
    /**
     * Check if worker needs additional skin protection
     * Used for hygiene compliance monitoring
     */
    public boolean needsAdditionalProtection(SkinDetectionResult result) {
        return result.requiresCoverage || 
               "EXTREME".equals(result.sunSensitivity) ||
               "HIGH".equals(result.sunSensitivity);
    }
}
